version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip3 install cfn-lint boto3
  
  build:
    commands:
      - echo "========================================="
      - echo "Cluster Name: $CLUSTER_NAME"
      - echo "Target Environment: $TARGET_ENV"
      - echo "========================================="
      - echo "Running cfn-lint validation on VPC template..."
      - cfn-lint $CLUSTER_NAME/cfn/vpc.yaml
      - echo "VPC template validation passed!"
      - echo "Running cfn-lint validation on EKS cluster template..."
      - cfn-lint $CLUSTER_NAME/cfn/eks-cluster.yaml
      - echo "EKS cluster template validation passed!"
      - echo "========================================="
      - echo "All validations completed successfully!"
      - echo "========================================="
