version: 0.2

phases:
  install:
    commands:
      - set -eu
      - echo "Installing dependencies..."
      - pip3 install cfn-lint boto3
  
  build:
    commands:
      - set -eu
      - echo "Packaging artifacts..."
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > commit_id.txt
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  name: artifact-$CODEBUILD_RESOLVED_SOURCE_VERSION
